# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest2softwaretesting():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test2softwaretesting(self):
    self.driver.get("https://software-testing.ru/")
    self.driver.set_window_size(1604, 904)
    self.driver.find_element(By.LINK_TEXT, "Школа технического директора от Стратоплана, скидка нашим читателям").click()
    self.driver.find_element(By.CSS_SELECTOR, ".item3 span").click()
    self.driver.find_element(By.LINK_TEXT, "Автоматизация тестирования").click()
    self.driver.find_element(By.LINK_TEXT, "Как QA-инженер может влиять на unit-тесты").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
  
