# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://www.youtube.com/")
    self.driver.set_window_size(1134, 759)
    element = self.driver.find_element(By.ID, "logo-icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.ID, "guide-icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ytd-mini-guide-renderer:nth-child(1) > #endpoint")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".ytd-mini-guide-renderer:nth-child(4) > #endpoint").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".style-scope:nth-child(4) > #endpoint > #icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".style-scope:nth-child(4) > #endpoint > #icon").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".ytd-mini-guide-renderer:nth-child(5) > #endpoint").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ytd-mini-guide-renderer:nth-child(5) > #endpoint")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#button > #button > .ytd-topbar-menu-button-renderer").click()
    self.driver.find_element(By.CSS_SELECTOR, "#button > #button > .ytd-topbar-menu-button-renderer").click()
    self.driver.find_element(By.CSS_SELECTOR, "#search-form > #container").click()
    self.driver.find_element(By.NAME, "search_query").send_keys("selenium ide ")
    self.driver.find_element(By.NAME, "search_query").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "search_query").send_keys(Keys.ENTER)
    element = self.driver.find_element(By.CSS_SELECTOR, ".ytd-item-section-renderer:nth-child(1) > #dismissible #video-title > .style-scope:nth-child(2)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.execute_script("window.scrollTo(0,1198)")
    self.driver.execute_script("window.scrollTo(0,1189)")
    element = self.driver.find_element(By.CSS_SELECTOR, "#buttons > .style-scope:nth-child(2) .yt-spec-touch-feedback-shape__fill")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "logo-icon").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#contents > .style-scope:nth-child(1) > #contents > .style-scope:nth-child(3) > #content .yt-core-image--fill-parent-height")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
